"""
Pytest测试生成器MCP服务器

本MCP服务器提供pytest+requests+allure格式的测试脚本生成功能：
- 从API上下文生成pytest测试代码
- 支持requests库进行HTTP请求
- 集成Allure报告框架
- 支持参数化测试和数据驱动

主要工具：
1. generate_pytest_tests: 从测试计划生成pytest测试文件
2. generate_test_fixtures: 生成pytest fixtures
3. generate_conftest: 生成conftest.py配置文件
"""



import os
import json
from datetime import datetime
from contextlib import asynccontextmanager
from typing import Any, AsyncIterator, Optional

from fastmcp import FastMCP, Context
from pydantic import BaseModel, Field

from api_agent.models.schemas import (
    TestCase, TestSuite, TestPlan, TestStep, 
    HttpMethod, TestPriority, GeneratedTestFile, GenerationResult
)


# ============================================================================
# 数据模型
# ============================================================================

class PytestGeneratorContext:
    """Pytest生成器上下文"""
    def __init__(self, output_dir: str = "./generated_tests"):
        self.output_dir = output_dir
        self.generated_files: list[GeneratedTestFile] = []
# pragma: no cover  MC80OmFIVnBZMlhwZ3JIa3VwSHBuSjQ2UlhGQk1nPT06MzJlMTFlZTk=


@asynccontextmanager
async def server_lifespan(server: FastMCP) -> AsyncIterator[PytestGeneratorContext]:
    """管理服务器生命周期"""
    config = server.config or {}
    output_dir = config.get("output_dir", "./generated_tests")
    
    # 确保输出目录存在
    os.makedirs(output_dir, exist_ok=True)
    
    context = PytestGeneratorContext(output_dir=output_dir)
    yield context


# 创建MCP服务器实例
mcp = FastMCP(name="PytestGenerator", lifespan=server_lifespan)


# ============================================================================
# 代码生成模板
# ============================================================================

PYTEST_IMPORTS_TEMPLATE = '''"""
{description}

Generated by API Automation Testing Agent
Generated at: {timestamp}
"""

import json
import pytest
import allure
import requests
from typing import Any, Optional
'''

CONFTEST_TEMPLATE = '''"""
Pytest配置文件 - 共享fixtures和配置

Generated by API Automation Testing Agent
"""

import pytest
import requests
import allure
from typing import Generator, Optional

# API基础配置
BASE_URL = "{base_url}"
DEFAULT_TIMEOUT = 30


@pytest.fixture(scope="session")
def base_url() -> str:
    """返回API基础URL"""
    return BASE_URL


@pytest.fixture(scope="session")
def session() -> Generator[requests.Session, None, None]:
    """创建共享的requests session"""
    with requests.Session() as session:
        session.headers.update({{
            "Content-Type": "application/json",
            "Accept": "application/json"
        }})
        yield session


@pytest.fixture(scope="session")
def auth_token(session: requests.Session, base_url: str) -> Optional[str]:
    """获取认证token (根据实际API修改)"""
    # TODO: 实现认证逻辑
    # response = session.post(f"{{base_url}}/auth/login", json={{...}})
    # return response.json().get("token")
    return None


@pytest.fixture
def api_client(session: requests.Session, base_url: str, auth_token: Optional[str]):
    """创建API客户端fixture"""
    class APIClient:
        def __init__(self):
            self.session = session
            self.base_url = base_url
            if auth_token:
                self.session.headers["Authorization"] = f"Bearer {{auth_token}}"
        
        def request(self, method: str, endpoint: str, **kwargs) -> requests.Response:
            url = f"{{self.base_url}}{{endpoint}}"
            kwargs.setdefault("timeout", DEFAULT_TIMEOUT)
            response = self.session.request(method, url, **kwargs)
            # 自动附加请求和响应到Allure报告
            self._attach_to_allure(method, endpoint, kwargs, response)
            return response
        
        def _attach_to_allure(self, method: str, endpoint: str, kwargs: dict, response: requests.Response):
            """将请求和响应附加到Allure报告"""
            # 附加请求信息
            request_info = {{
                "method": method,
                "url": f"{{self.base_url}}{{endpoint}}",
                "headers": dict(self.session.headers),
                "params": kwargs.get("params"),
                "json": kwargs.get("json"),
            }}
            allure.attach(
                json.dumps(request_info, indent=2, ensure_ascii=False),
                "请求信息",
                allure.attachment_type.JSON
            )
            
            # 附加响应信息
            try:
                response_body = response.json()
            except:
                response_body = response.text
            
            response_info = {{
                "status_code": response.status_code,
                "headers": dict(response.headers),
                "body": response_body,
                "elapsed_ms": response.elapsed.total_seconds() * 1000
            }}
            allure.attach(
                json.dumps(response_info, indent=2, ensure_ascii=False),
                "响应信息",
                allure.attachment_type.JSON
            )
        
        def get(self, endpoint: str, **kwargs) -> requests.Response:
            return self.request("GET", endpoint, **kwargs)
        
        def post(self, endpoint: str, **kwargs) -> requests.Response:
            return self.request("POST", endpoint, **kwargs)
        
        def put(self, endpoint: str, **kwargs) -> requests.Response:
            return self.request("PUT", endpoint, **kwargs)
        
        def delete(self, endpoint: str, **kwargs) -> requests.Response:
            return self.request("DELETE", endpoint, **kwargs)
        
        def patch(self, endpoint: str, **kwargs) -> requests.Response:
            return self.request("PATCH", endpoint, **kwargs)
    
    return APIClient()
'''


# ============================================================================
# 辅助函数
# ============================================================================

def _sanitize_name(name: str) -> str:
    """将名称转换为有效的Python标识符"""
    sanitized = name.lower()
    for char in [' ', '-', '.', '/', '\\', ':', '(', ')', '[', ']', '{', '}']:
        sanitized = sanitized.replace(char, '_')
    while '__' in sanitized:
        sanitized = sanitized.replace('__', '_')
    sanitized = sanitized.strip('_')
    if sanitized and sanitized[0].isdigit():
        sanitized = f"test_{sanitized}"
    return sanitized or "test_unnamed"

# noqa  MS80OmFIVnBZMlhwZ3JIa3VwSHBuSjQ2UlhGQk1nPT06MzJlMTFlZTk=

def _get_priority_marker(priority: TestPriority) -> str:
    """获取优先级对应的pytest marker"""
    markers = {
        TestPriority.CRITICAL: '@pytest.mark.critical',
        TestPriority.HIGH: '@pytest.mark.high',
        TestPriority.MEDIUM: '@pytest.mark.medium',
        TestPriority.LOW: '@pytest.mark.low'
    }
    return markers.get(priority, '@pytest.mark.medium')


def _get_allure_severity(priority: TestPriority) -> str:
    """获取优先级对应的Allure severity"""
    severity_map = {
        TestPriority.CRITICAL: 'allure.severity_level.CRITICAL',
        TestPriority.HIGH: 'allure.severity_level.NORMAL',
        TestPriority.MEDIUM: 'allure.severity_level.MINOR',
        TestPriority.LOW: 'allure.severity_level.TRIVIAL'
    }
    return severity_map.get(priority, 'allure.severity_level.NORMAL')


def _generate_step_code(step: TestStep, indent: str = "    ") -> str:
    """生成测试步骤代码"""
    lines = []
    
    # 添加allure步骤装饰
    lines.append(f'{indent}with allure.step("{step.name}"):')
    step_indent = indent + "    "
    
    # 构建请求参数
    method = step.method.value.lower()
    endpoint = step.endpoint
    
    # 处理路径参数
    for param_name, param_value in step.path_params.items():
        endpoint = endpoint.replace(f"{{{param_name}}}", str(param_value))
    
    # 构建请求调用
    request_args = []
    if step.query_params:
        request_args.append(f"params={json.dumps(step.query_params)}")
    if step.headers:
        request_args.append(f"headers={json.dumps(step.headers)}")
    if step.request_body:
        request_args.append(f"json={json.dumps(step.request_body)}")
    
    args_str = ", ".join(request_args)
    if args_str:
        lines.append(f'{step_indent}response = api_client.{method}("{endpoint}", {args_str})')
    else:
        lines.append(f'{step_indent}response = api_client.{method}("{endpoint}")')
    
    # 生成断言
    for assertion in step.assertions:
        if assertion.assertion_type == "status_code":
            lines.append(f'{step_indent}assert response.status_code == {assertion.expected_value}, '
                        f'f"Expected status {assertion.expected_value}, got {{response.status_code}}"')
        elif assertion.assertion_type == "json_path":
            lines.append(f'{step_indent}response_json = response.json()')
            lines.append(f'{step_indent}# TODO: 验证JSON路径 {assertion.actual_path}')
        elif assertion.assertion_type == "response_time":
            lines.append(f'{step_indent}assert response.elapsed.total_seconds() * 1000 < {assertion.expected_value}, '
                        f'"Response time exceeded {assertion.expected_value}ms"')
    
    # 提取变量
    if step.extract_variables:
        lines.append(f'{step_indent}response_json = response.json()')
        for var_name, json_path in step.extract_variables.items():
            lines.append(f'{step_indent}# 提取变量: {var_name} from {json_path}')
    
    return "\n".join(lines)


def _generate_test_case_code(test_case: TestCase) -> str:
    """生成单个测试用例代码"""
    func_name = f"test_{_sanitize_name(test_case.name)}"
    
    lines = []
    
    # 添加allure装饰器
    lines.append(f'@allure.title("{test_case.name}")')
    lines.append(f'@allure.description("""{test_case.description}""")')
    lines.append(f'@allure.severity({_get_allure_severity(test_case.priority)})')
    
    # 添加标签
    for tag in test_case.tags:
        lines.append(f'@allure.tag("{tag}")')
    
    # 添加优先级marker
    lines.append(_get_priority_marker(test_case.priority))
# pragma: no cover  Mi80OmFIVnBZMlhwZ3JIa3VwSHBuSjQ2UlhGQk1nPT06MzJlMTFlZTk=
    
    # 函数定义
    lines.append(f'def {func_name}(api_client):')
    lines.append(f'    """')
    lines.append(f'    {test_case.description or test_case.name}')
    if test_case.preconditions:
        lines.append(f'    ')
        lines.append(f'    Preconditions:')
        for pre in test_case.preconditions:
            lines.append(f'    - {pre}')
    lines.append(f'    """')
    
    # Setup步骤
    if test_case.setup_steps:
        lines.append('    # Setup')
        for step in test_case.setup_steps:
            lines.append(_generate_step_code(step, "    "))
    
    # 主测试步骤
    lines.append('    # Test Steps')
    for step in test_case.steps:
        lines.append(_generate_step_code(step, "    "))
    
    # Teardown步骤
    if test_case.teardown_steps:
        lines.append('    # Teardown')
        for step in test_case.teardown_steps:
            lines.append(_generate_step_code(step, "    "))

    return "\n".join(lines)


# ============================================================================
# MCP工具
# ============================================================================

@mcp.tool()
async def generate_pytest_tests(
    test_suite_json: str,
    output_dir: Optional[str] = None,
    ctx: Context = None
) -> str:
    """
    从测试套件生成pytest测试文件

    参数：
        test_suite_json: TestSuite的JSON字符串
        output_dir: 输出目录（可选）

    返回：
        生成结果的JSON字符串
    """
    try:
        suite_data = json.loads(test_suite_json)
        test_suite = TestSuite(**suite_data)

        context = ctx.request_context.lifespan_context
        out_dir = output_dir or context.output_dir
        os.makedirs(out_dir, exist_ok=True)

        generated_files = []
        timestamp = datetime.now().isoformat()

        file_name = f"test_{_sanitize_name(test_suite.name)}.py"
        file_path = os.path.join(out_dir, file_name)

        content_lines = [
            PYTEST_IMPORTS_TEMPLATE.format(
                description=f"API测试: {test_suite.name}",
                timestamp=timestamp
            )
        ]

        content_lines.append(f'\n@allure.feature("{test_suite.name}")')
        content_lines.append(f'class Test{_sanitize_name(test_suite.name).title().replace("_", "")}:')
        content_lines.append(f'    """{test_suite.description or test_suite.name}"""')
        content_lines.append('')

        for test_case in test_suite.test_cases:
            case_code = _generate_test_case_code(test_case)
            indented_code = "\n".join("    " + line if line.strip() else line
                                      for line in case_code.split("\n"))
            content_lines.append(indented_code)
            content_lines.append('')

        content = "\n".join(content_lines)

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)

        generated_files.append(GeneratedTestFile(
            file_path=file_path,
            file_name=file_name,
            content=content,
            language="python",
            framework="pytest"
        ))

        result = GenerationResult(
            success=True,
            message=f"成功生成 {len(generated_files)} 个测试文件",
            files=generated_files
        )
# pragma: no cover  My80OmFIVnBZMlhwZ3JIa3VwSHBuSjQ2UlhGQk1nPT06MzJlMTFlZTk=

        return result.model_dump_json(indent=2)

    except Exception as e:
        result = GenerationResult(
            success=False,
            message=f"生成失败: {str(e)}",
            errors=[str(e)]
        )
        return result.model_dump_json(indent=2)


@mcp.tool()
async def generate_conftest(
    base_url: str,
    output_dir: Optional[str] = None,
    auth_config: Optional[str] = None,
    ctx: Context = None
) -> str:
    """
    生成pytest的conftest.py配置文件

    参数：
        base_url: API基础URL
        output_dir: 输出目录（可选）
        auth_config: 认证配置JSON（可选）

    返回：
        生成结果的JSON字符串
    """
    try:
        context = ctx.request_context.lifespan_context
        out_dir = output_dir or context.output_dir
        os.makedirs(out_dir, exist_ok=True)

        file_path = os.path.join(out_dir, "conftest.py")
        content = CONFTEST_TEMPLATE.format(base_url=base_url)

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)

        result = GenerationResult(
            success=True,
            message="成功生成conftest.py",
            files=[GeneratedTestFile(
                file_path=file_path,
                file_name="conftest.py",
                content=content,
                language="python",
                framework="pytest"
            )]
        )

        return result.model_dump_json(indent=2)

    except Exception as e:
        return GenerationResult(
            success=False,
            message=f"生成失败: {str(e)}",
            errors=[str(e)]
        ).model_dump_json(indent=2)


@mcp.tool()
async def generate_pytest_ini(
    output_dir: Optional[str] = None,
    markers: Optional[list[str]] = None,
    ctx: Context = None
) -> str:
    """
    生成pytest.ini配置文件

    参数：
        output_dir: 输出目录（可选）
        markers: 自定义markers列表（可选）

    返回：
        生成结果的JSON字符串
    """
    try:
        context = ctx.request_context.lifespan_context
        out_dir = output_dir or context.output_dir
        os.makedirs(out_dir, exist_ok=True)

        default_markers = [
            "critical: 关键测试",
            "high: 高优先级测试",
            "medium: 中优先级测试",
            "low: 低优先级测试",
            "smoke: 冒烟测试",
            "regression: 回归测试",
            "integration: 集成测试"
        ]

        all_markers = default_markers + (markers or [])

        content = f'''[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --alluredir=./allure-results
markers =
    {chr(10).join("    " + m for m in all_markers)}
'''

        file_path = os.path.join(out_dir, "pytest.ini")
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)

        return GenerationResult(
            success=True,
            message="成功生成pytest.ini",
            files=[GeneratedTestFile(
                file_path=file_path,
                file_name="pytest.ini",
                content=content,
                language="ini",
                framework="pytest"
            )]
        ).model_dump_json(indent=2)

    except Exception as e:
        return GenerationResult(
            success=False,
            message=f"生成失败: {str(e)}",
            errors=[str(e)]
        ).model_dump_json(indent=2)


@mcp.tool()
async def generate_requirements(
    output_dir: Optional[str] = None,
    extra_packages: Optional[list[str]] = None,
    ctx: Context = None
) -> str:
    """
    生成测试依赖的requirements.txt

    参数：
        output_dir: 输出目录（可选）
        extra_packages: 额外的依赖包（可选）

    返回：
        生成结果的JSON字符串
    """
    try:
        context = ctx.request_context.lifespan_context
        out_dir = output_dir or context.output_dir
        os.makedirs(out_dir, exist_ok=True)

        packages = [
            "pytest>=7.0.0",
            "pytest-xdist>=3.0.0",
            "pytest-rerunfailures>=12.0",
            "pytest-timeout>=2.2.0",
            "allure-pytest>=2.13.0",
            "requests>=2.28.0",
            "jsonpath-ng>=1.5.0",
            "python-dotenv>=1.0.0",
            "pydantic>=2.0.0"
        ]

        if extra_packages:
            packages.extend(extra_packages)

        content = "\n".join(packages)
        file_path = os.path.join(out_dir, "requirements.txt")

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)

        return GenerationResult(
            success=True,
            message="成功生成requirements.txt",
            files=[GeneratedTestFile(
                file_path=file_path,
                file_name="requirements.txt",
                content=content,
                language="text",
                framework="pytest"
            )]
        ).model_dump_json(indent=2)

    except Exception as e:
        return GenerationResult(
            success=False,
            message=f"生成失败: {str(e)}",
            errors=[str(e)]
        ).model_dump_json(indent=2)


# ============================================================================
# 主入口点
# ============================================================================

def main():
    """主入口点"""
    import argparse

    parser = argparse.ArgumentParser(description="Pytest Generator MCP Server")
    parser.add_argument(
        "--output-dir", type=str, default="./generated_tests",
        help="默认输出目录"
    )
    parser.add_argument(
        "--port", type=int, default=8005,
        help="SSE服务器端口号"
    )
    parser.add_argument(
        "--sse", action="store_true", default=True,
        help="启用SSE模式"
    )
    args = parser.parse_args()

    mcp.config = {
        "output_dir": args.output_dir
    }

    if args.sse:
        mcp.run(transport="sse", port=args.port, host="0.0.0.0")
    else:
        mcp.run()


if __name__ == "__main__":
    main()
