analysis:
  mcp:
    playwright_mcp:
      server_name: "playwright"
      transport: "stdio"
      command: "npx"
      args:
        - "@playwright/mcp"
      env: {}

chrome_mcp:
  server_name: "midscene-web"
  transport: "streamable_http"
  url: "http://127.0.0.1:12306/mcp"

chart_mcp:
  command: "npx"
  args:
    - "-y"
    - "@antv/mcp-server-chart"
